import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt
img1 = cv.imread('C:\Dev\DIP\Open CV\photos\Lenna.png', 0)  
img2 = cv.imread('C:\Dev\DIP\Open CV\photos\IMG20200821113912.jpg', 0)  
hist1, _ = np.histogram(img1.flatten(), bins=256, range=(0, 256))
hist2, _ = np.histogram(img2.flatten(), bins=256, range=(0, 256))
cdf1 = hist1.cumsum()
cdf2 = hist2.cumsum()
cdf1_normal = (cdf1 - cdf1.min()) * 255 / (cdf1.max() - cdf1.min())
cdf2_normal = (cdf2 - cdf2.min()) * 255 / (cdf2.max() - cdf2.min())
match_img = np.interp(img1.flatten(), range(0, 256), cdf1_normal).reshape(img1.shape)
match_img = np.interp(match_img.flatten(), cdf1_normal, cdf2_normal).reshape(img1.shape)
plt.figure(figsize=(8, 4))
plt.subplot(1, 2, 1)
plt.title('Original Image 1')
plt.imshow(img1, cmap='gray')
plt.axis('off')
plt.subplot(1, 2, 2)
plt.title('Matched Image 2')
plt.imshow(match_img, cmap='gray')
plt.axis('off')
plt.tight_layout()
plt.show()
